version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      TZ: America/Sao_Paulo
  adminer:
    image: adminer
    ports:
      - "8080:8080"